machine:
  services:
    - docker

dependencies:
  cache_directories:
    - "~/docker"
  override:
    - docker info
    - if [[ -e ~/docker/image.tar ]]; then docker load --input ~/docker/image.tar; fi
    - docker build -t 28mm/blast-radius .
    - mkdir -p ~/docker; docker save 28mm/blast-radius > ~/docker/image.tar

test:
  override:
    - true

deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push 28mm/blast-radius